name: Manual Release (Go)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Git tag to create
        required: true
        default: v1.0.0
      name:
        description: Release name
        required: false
      prerelease:
        description: Mark as pre-release
        required: true
        type: boolean
        default: false
      package:
        description: Go package/main path to build
        required: true
        default: .
      binary_name:
        description: Output binary name
        required: false
        default: hive-connector

permissions:
  contents: write
  actions: read

env:
  GO_VERSION: "1.22.x"

jobs:
  build:
    name: Build ${{ github.event.inputs.tag }} for ${{ matrix.goos }}/${{ matrix.goarch }}${{ matrix.goarm && format(' (armv{0})', matrix.goarm) || '' }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
            goarm: ""
            ext: ""
            archive: tar.gz
          - goos: linux
            goarch: arm64
            goarm: ""
            ext: ""
            archive: tar.gz
          - goos: linux
            goarch: arm
            goarm: "7"
            ext: ""
            archive: tar.gz
          - goos: windows
            goarch: amd64
            goarm: ""
            ext: ".exe"
            archive: zip
          - goos: windows
            goarch: arm64
            goarm: ""
            ext: ".exe"
            archive: zip
          - goos: darwin
            goarch: amd64
            goarm: ""
            ext: ""
            archive: tar.gz
          - goos: darwin
            goarch: arm64
            goarm: ""
            ext: ""
            archive: tar.gz

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Resolve binary name
        id: names
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${{ github.event.inputs.binary_name }}" ]; then
            BIN="${{ github.event.inputs.binary_name }}"
          else
            BIN="$(basename "${GITHUB_REPOSITORY}")"
          fi
          echo "bin=${BIN}" >> "$GITHUB_OUTPUT"

      - name: Build and package
        shell: bash
        run: |
          set -euo pipefail

          TAG="${{ github.event.inputs.tag }}"
          PKG="${{ github.event.inputs.package }}"
          NAME="${{ steps.names.outputs.bin }}"
          GOOS="${{ matrix.goos }}"
          GOARCH="${{ matrix.goarch }}"
          GOARM="${{ matrix.goarm }}"
          EXT="${{ matrix.ext }}"
          ARCHIVE="${{ matrix.archive }}"

          # Output directories
          mkdir -p "dist/${TAG}"
          OUTDIR="dist/${TAG}/${NAME}_${TAG}_${GOOS}_${GOARCH}"
          if [ -n "${GOARM}" ]; then
            OUTDIR="dist/${TAG}/${NAME}_${TAG}_${GOOS}_armv${GOARM}"
          fi
          mkdir -p "${OUTDIR}"

          # Build
          export CGO_ENABLED=0
          export GOOS GOARCH
          if [ -n "${GOARM}" ]; then export GOARM; fi

          echo "Building ${NAME} for ${GOOS}/${GOARCH}${GOARM:+ (armv${GOARM})}"
          go mod download
          go build -trimpath -ldflags "-s -w -X main.version=${TAG}" -o "${OUTDIR}/${NAME}${EXT}" "${PKG}"

          # Attach common docs if present
          [ -f LICENSE ] && cp LICENSE "${OUTDIR}/"
          [ -f README.md ] && cp README.md "${OUTDIR}/"

          # Package
          pushd "dist/${TAG}" >/dev/null
          case "${ARCHIVE}" in
            zip)
              if [ -n "${GOARM}" ]; then
                ARCHIVE_NAME="${NAME}_${TAG}_${GOOS}_armv${GOARM}.zip"
              else
                ARCHIVE_NAME="${NAME}_${TAG}_${GOOS}_${GOARCH}.zip"
              fi
              (cd "$(basename "${OUTDIR}")" && zip -r "../${ARCHIVE_NAME}" .)
              ;;
            tar.gz)
              if [ -n "${GOARM}" ]; then
                ARCHIVE_NAME="${NAME}_${TAG}_${GOOS}_armv${GOARM}.tar.gz"
              else
                ARCHIVE_NAME="${NAME}_${TAG}_${GOOS}_${GOARCH}.tar.gz"
              fi
              (cd "$(basename "${OUTDIR}")" && tar -czf "../${ARCHIVE_NAME}" .)
              ;;
          esac
          popd >/dev/null

          # Checksums
          pushd "dist/${TAG}" >/dev/null
          sha256sum *.zip *.tar.gz 2>/dev/null | sort -k2 > SHA256SUMS
          popd >/dev/null

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm && format('-armv{0}', matrix.goarm) || '' }}
          path: |
            dist/${{ github.event.inputs.tag }}/*.zip
            dist/${{ github.event.inputs.tag }}/*.tar.gz
            dist/${{ github.event.inputs.tag }}/SHA256SUMS
          if-no-files-found: error
          retention-days: 7

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: List files
        run: |
          echo "Downloaded files:"
          find dist -type f -maxdepth 2 -print

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.name || github.event.inputs.tag }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          generate_release_notes: true
          files: |
            dist/**/*.zip
            dist/**/*.tar.gz
            dist/**/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
